package com.kakeipocket.KakeiPocket.services.export;

import com.kakeipocket.KakeiPocket.dto.Admin.AdminDashboardSummaryResponse;

import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Low-level Excel writer using Apache POI.
 * Produces .xlsx workbooks from in-memory data and styling.
 *
 * Designed so that {@link AdminExportService} only deals with data and
 * presentation; this class owns all POI types.
 */
@Component
public class ExcelGenerator {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final DateTimeFormatter DATETIME_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private static final String EMPTY_CELL = "-";

    /**
     * Build a workbook that wraps a generated byte[] payload.
     */
    public byte[] writeToBytes(Workbook workbook) throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        workbook.write(out);
        workbook.close();
        return out.toByteArray();
    }

    public XSSFWorkbook createWorkbook() {
        return new XSSFWorkbook();
    }

    public SXSSFWorkbook createStreamingWorkbook(int rowAccessWindow) {
        return new SXSSFWorkbook(new XSSFWorkbook(), rowAccessWindow);
    }

    public CellStyle headerStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setBold(true);
        font.setColor(IndexedColors.WHITE.getIndex());
        font.setFontHeightInPoints((short) 11);
        style.setFont(font);
        style.setFillForegroundColor(
                IndexedColors.DARK_BLUE.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setAlignment(HorizontalAlignment.CENTER);
        applyBorders(style);
        return style;
    }

    public CellStyle textStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        applyBorders(style);
        return style;
    }

    public CellStyle numberStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        DataFormat fmt = wb.createDataFormat();
        style.setDataFormat(fmt.getFormat("#,##0.##"));
        applyBorders(style);
        return style;
    }

    public CellStyle currencyStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        DataFormat fmt = wb.createDataFormat();
        style.setDataFormat(fmt.getFormat("#,##0.00"));
        applyBorders(style);
        return style;
    }

    public CellStyle dateStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        DataFormat fmt = wb.createDataFormat();
        style.setDataFormat(fmt.getFormat("yyyy-mm-dd"));
        applyBorders(style);
        return style;
    }

    public CellStyle dateTimeStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        DataFormat fmt = wb.createDataFormat();
        style.setDataFormat(fmt.getFormat("yyyy-mm-dd hh:mm:ss"));
        applyBorders(style);
        return style;
    }

    private void applyBorders(CellStyle style) {
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
    }

    public Sheet createSheet(Workbook wb, String name) {
        Sheet sheet = wb.createSheet(name);
        // Freeze header row
        sheet.createFreezePane(0, 1);
        return sheet;
    }

    public Row writeHeaderRow(Sheet sheet, String[] headers,
                              int rowIndex) {
        Row row = sheet.createRow(rowIndex);
        CellStyle style = headerStyle(sheet.getWorkbook());
        for (int i = 0; i < headers.length; i++) {
            Cell cell = row.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(style);
        }
        return row;
    }

    public void autoSizeColumns(Sheet sheet, int columnCount) {
        for (int i = 0; i < columnCount; i++) {
            try {
                sheet.autoSizeColumn(i);
            } catch (Exception ignored) {
                // some POI impls throw on certain JVMs
            }
        }
    }

    public void writeTextCell(Row row, int col, String value,
                              CellStyle style) {
        Cell cell = row.createCell(col);
        cell.setCellValue(value != null ? value : EMPTY_CELL);
        if (style != null) {
            cell.setCellStyle(style);
        }
    }

    public void writeNumberCell(Row row, int col, BigDecimal value,
                                CellStyle style) {
        Cell cell = row.createCell(col);
        if (value != null) {
            cell.setCellValue(value.doubleValue());
        }
        if (style != null) {
            cell.setCellStyle(style);
        }
    }

    public void writeLongCell(Row row, int col, Long value,
                              CellStyle style) {
        Cell cell = row.createCell(col);
        if (value != null) {
            cell.setCellValue(value.doubleValue());
        }
        if (style != null) {
            cell.setCellStyle(style);
        }
    }

    public void writeIntCell(Row row, int col, Integer value,
                            CellStyle style) {
        Cell cell = row.createCell(col);
        if (value != null) {
            cell.setCellValue(value.doubleValue());
        }
        if (style != null) {
            cell.setCellStyle(style);
        }
    }

    public void writeDateCell(Row row, int col, LocalDate value,
                              CellStyle style) {
        Cell cell = row.createCell(col);
        if (value != null) {
            cell.setCellValue(value.format(DATE_FMT));
        }
        if (style != null) {
            cell.setCellStyle(style);
        }
    }

    public void writeDateTimeCell(Row row, int col, LocalDateTime value,
                                  CellStyle style) {
        Cell cell = row.createCell(col);
        if (value != null) {
            cell.setCellValue(value.format(DATETIME_FMT));
        }
        if (style != null) {
            cell.setCellStyle(style);
        }
    }

    public void writeEmptyRows(Sheet sheet, int rowIndex, int count) {
        CellStyle style = textStyle(sheet.getWorkbook());
        for (int i = 0; i < count; i++) {
            Row row = sheet.createRow(rowIndex + i);
            writeTextCell(row, 0, "No data", style);
        }
    }

    public void mergeAndTitle(Sheet sheet, int rowIndex, int columnCount,
                              String title) {
        Row row = sheet.createRow(rowIndex);
        Cell cell = row.createCell(0);
        cell.setCellValue(title);
        CellStyle titleStyle = sheet.getWorkbook().createCellStyle();
        Font font = sheet.getWorkbook().createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 14);
        titleStyle.setFont(font);
        cell.setCellStyle(titleStyle);
        sheet.addMergedRegion(
                new CellRangeAddress(
                        rowIndex, rowIndex, 0, columnCount - 1));
    }

    /**
     * Convenience helper for summary style sheets (Metric / Value).
     */
    public void writeKeyValueRow(
            Sheet sheet,
            int rowIndex,
            String label,
            Object value,
            CellStyle labelStyle,
            CellStyle valueStyle
    ) {
        Row row = sheet.createRow(rowIndex);
        writeTextCell(row, 0, label, labelStyle);
        if (value == null) {
            writeTextCell(row, 1, EMPTY_CELL, valueStyle);
        } else if (value instanceof Number) {
            writeNumberCell(row, 1, new BigDecimal(value.toString()),
                    valueStyle);
        } else {
            writeTextCell(row, 1, value.toString(), valueStyle);
        }
    }

    public <T> boolean isEmpty(List<T> list) {
        return list == null || list.isEmpty();
    }

    /**
     * Summary holder passed to writeSummarySheet().
     */
    public record SummaryEntry(
            String label, Object value
    ) {}

    public void writeSummarySheet(
            Sheet sheet,
            List<SummaryEntry> entries
    ) {
        mergeAndTitle(sheet, 0, 2, "KakeiPocket — System Summary");
        Row headerRow = writeHeaderRow(
                sheet, new String[]{"Metric", "Value"}, 1);
        CellStyle labelStyle = headerStyle(sheet.getWorkbook());
        CellStyle valueStyle = textStyle(sheet.getWorkbook());

        int rowIndex = 2;
        for (SummaryEntry entry : entries) {
            Row row = sheet.createRow(rowIndex++);
            Cell labelCell = row.createCell(0);
            labelCell.setCellValue(entry.label());
            labelCell.setCellStyle(labelStyle);

            Cell valueCell = row.createCell(1);
            Object v = entry.value();
            if (v == null) {
                valueCell.setCellValue(EMPTY_CELL);
            } else if (v instanceof BigDecimal) {
                valueCell.setCellValue(
                        ((BigDecimal) v).doubleValue());
                valueCell.setCellStyle(currencyStyle(
                        sheet.getWorkbook()));
            } else if (v instanceof Number) {
                valueCell.setCellValue(
                        ((Number) v).doubleValue());
                valueCell.setCellStyle(numberStyle(
                        sheet.getWorkbook()));
            } else {
                valueCell.setCellValue(v.toString());
            }
            valueCell.setCellStyle(
                    valueCell.getCellStyle() != null
                            ? valueCell.getCellStyle()
                            : valueStyle);
        }

        autoSizeColumns(sheet, 2);
    }

    /**
     * Quick accessor used by AdminExportService to fetch the dashboard
     * summary that drives the Statistics report.
     */
    public SummaryEntry dashboardEntry(
            AdminDashboardSummaryResponse summary,
            String label,
            java.util.function.Function<
                    AdminDashboardSummaryResponse, ?> extractor
    ) {
        return new SummaryEntry(label, extractor.apply(summary));
    }
}